In [3]:
# List Comprehension


# Traditional Way

Vegetable=["Potato","Onion","BottleGaurd"]

Nlist=[]

for i in Vegetable:
     if "P" in i:
         Nlist.append(i)
print(Nlist)


['Potato']


In [5]:
# LC Way:

Vegetable=["Potato","Onion","BottleGaurd"]
Nlist=[i for i in Vegetable if "P" in i]
print(Nlist)




['Potato']


In [6]:
newlist=[i for i in range(10)]

In [7]:
newlist

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
newlist=[i for i in range(10) if i>4]

In [9]:
newlist

[5, 6, 7, 8, 9]

In [10]:
## Copying of List

newlist1=newlist.copy()

In [12]:
newlist1.

[5, 6, 7, 8, 9]

In [13]:
newlist

[5, 6, 7, 8, 9]

In [ ]:
## List Assessment 


# clear()



## Tuple

In [14]:
tuple1=[1,2,3,4,5]

In [15]:
type(tuple1)

list

In [16]:
tuple1=(1,2,3,4,5)

In [17]:
type(tuple1)

tuple

In [21]:
# indexing

tuple1[:]

(1, 2, 3, 4, 5)

In [23]:
tuple1[3]

4

In [24]:
tuple1[3]=5

TypeError: 'tuple' object does not support item assignment

In [25]:
len(tuple1)

5

In [26]:
tuple1[-1]

5

In [27]:
tuple1[1:4]

(2, 3, 4)

In [28]:
# in keyword: Check whether item is present or not

if 2 in tuple1:
    print("2 is present")

2 is present


In [29]:
tuple1

(1, 2, 3, 4, 5)

In [30]:
a=list(tuple1)

In [31]:
a

[1, 2, 3, 4, 5]

In [32]:
type(a)

list

In [33]:
a[2]="Devesh"

In [34]:
a

[1, 2, 'Devesh', 4, 5]

In [39]:
tuple1=tuple(a)

In [40]:
tuple1

(1, 2, 'Devesh', 4, 5)

In [38]:
type(b)

tuple

In [42]:
tuple2=(5,6,7,"Prarthana")
print(tuple1)
print(tuple2)

(1, 2, 'Devesh', 4, 5)
(5, 6, 7, 'Prarthana')


In [43]:
tuple1+tuple2

(1, 2, 'Devesh', 4, 5, 5, 6, 7, 'Prarthana')

In [44]:
tuple1

(1, 2, 'Devesh', 4, 5)

In [45]:
del tuple1

In [46]:
tuple1

NameError: name 'tuple1' is not defined

In [47]:
for i in tuple2:
    print(i)

5
6
7
Prarthana


In [49]:
tuple2.count(1)

0

In [50]:
tuple2.count(5)

1

In [51]:
tuple2.index(7)

2

## SET

In [52]:
a={1,2,3,4,4,4}

In [53]:
a

{1, 2, 3, 4}

In [54]:
type(a)

set

In [58]:
len(a)

4

In [59]:
set1={1,2,"Name",1.23}

In [60]:
set1

{1, 1.23, 2, 'Name'}

In [61]:
set1= set([1,2,3,4,5])

In [62]:
set1

{1, 2, 3, 4, 5}

In [63]:
for i in set1:
    print(i)

1
2
3
4
5


In [64]:
set1.add("Pavan")

In [65]:
set1

{1, 2, 3, 4, 5, 'Pavan'}

In [66]:
set2={2,3,4,5,6}

In [67]:
set1.intersection(set2)

{2, 3, 4, 5}

In [69]:
set1.intersection_update(set2)

In [70]:
set1

{2, 3, 4, 5}

In [71]:
set1.union(set2)

{2, 3, 4, 5, 6}

## Dictionary

In [75]:
dict1={"name1":"Priya", "name2":"Sudhanva", 23:"ArisGlobal", 1.29:2300000}

In [76]:
dict1

{'name1': 'Priya', 'name2': 'Sudhanva', 23: 'ArisGlobal', 1.29: 2300000}

In [74]:
type(dict1)

dict

In [77]:
len(dict1)

4

In [78]:
dict1={"car":"BMW", 
       "petrol": False, 
       "year":2020, 
       "colors":["red","blue","black"]
      }

In [79]:
dict1

{'car': 'BMW',
 'petrol': False,
 'year': 2020,
 'colors': ['red', 'blue', 'black']}

In [81]:
# Indexing 

dict1["car"]

'BMW'

In [82]:
dict1["colors"]

['red', 'blue', 'black']

In [84]:
dict1["colors"][2]

'black'

In [85]:
# get ( ) function

dict1.get("year")

2020

In [86]:
dict1.keys()

dict_keys(['car', 'petrol', 'year', 'colors'])

In [88]:
dict1.values()

dict_values(['BMW', False, 2020, ['red', 'blue', 'black']])

In [89]:
dict1

{'car': 'BMW',
 'petrol': False,
 'year': 2020,
 'colors': ['red', 'blue', 'black']}

In [90]:
dict1["year"]=2021
print(dict1)

{'car': 'BMW', 'petrol': False, 'year': 2021, 'colors': ['red', 'blue', 'black']}


In [91]:
dict1.items()

dict_items([('car', 'BMW'), ('petrol', False), ('year', 2021), ('colors', ['red', 'blue', 'black'])])

In [94]:
if "car" in dict1:
    print("car key is present")

car key is present


In [97]:
# nested dictionary

dict1={
    "buyername":{"name:John"},
    
    "car":"BMW", 
       "petrol": False, 
       "year":2020, 
       "colors":["red","blue","black"]
       
      }

In [98]:
dict1

{'buyername': {'name:John'},
 'car': 'BMW',
 'petrol': False,
 'year': 2020,
 'colors': ['red', 'blue', 'black']}

## Functions

In [99]:
def fun1():
    a=20
    b=30
    c=a+b
    print(c)

fun1()

50


In [101]:
def fun1():
    a=20
    b=30
    c=a+b
    return c

print("Summation of values",fun1())

Summation of values 50


In [ ]:
## Function with arguments:

def sum(a,b):
    return a+b


a=int(input("Enter the value of a: "))
b=int(input("Enter the value of b: "))

print("Summation is: ", sum(a,b))



## Required Argument Example

In [3]:
def fun2(name,ag=20):
    print("Name is",name,"and age is", ag)
    
fun2(name="Peter")

# Default argument

Name is Peter and age is 20


## Variable length arguments (*args)

In [9]:
def fun3(*name):
    print("type of passed argument is \n", type(name))
   
    print("passed Arguments are: ")
    
    for i in name:
        print(i)
        
fun3("Pavan","Sudhanva","Priyanka","Sandhya")

type of passed argument is 
 <class 'tuple'>
passed Arguments are: 
Pavan
Sudhanva
Priyanka
Sandhya


## Keyword Arguments:  **kwargs

In [14]:
def fun4(name,message):
    print("Printing the text with", name, "and ", message)
    
fun4(name="Ryan",message="How are You?")

Printing the text with Ryan and  How are You?


In [17]:
def fruit(**fname):
    print(fname)
    
fruit(b="banana")
fruit(fruit1="Mango",fruit2="Orange")

{'b': 'banana'}
{'fruit1': 'Mango', 'fruit2': 'Orange'}


In [18]:
a=-20.30


In [19]:
abs(a) # absolute value

20.3

## iter()

In [20]:
list1=[1,2,3,4,5]

for i in list1:
    print(i)

1
2
3
4
5


In [21]:
iter_list=iter(list1)

In [22]:
iter_list

In [23]:
print(next(iter_list))

1


In [28]:
print(next(iter_list)) # Error after the last element fetched.

StopIteration: 

## Lambda function:

In [29]:
a= lambda x : x + 10

print(a)
print("Addition", a(30))


<function <lambda> at 0x0000019CDA6AF940>
Addition 40


In [35]:
## Lambda is mostly used with map()

lst=[1,2,3,4,5]

sqr_lst= list(map(lambda x: x**2, lst))

In [36]:
print(sqr_lst)

[1, 4, 9, 16, 25]


In [38]:
def multiplication(a,b):
    return a*b
multiplication(2,3)

6

In [39]:
m= lambda a,b : a*b
print(m(2,3))

6


In [40]:
def fun1(n):
    return lambda i: i*n

double=fun1(2)

In [41]:
print(double(10))

20


In [42]:
tripple=fun1(3)
print(tripple(20))

60


In [50]:
list1=[10,22,37,41,100,123,29]

odd_val= tuple(filter(lambda x: x%3 == 0,list1))

In [51]:
print(odd_val)

(123,)


In [ ]:
#LEAP YEAR

year = int(input('Enter a year: '))
if (year % 400) == 0:
    print('{0} is a leap year'.format(year))
elif (year % 100) == 0:
    print('{0} is not a leap year'.format(year))
elif (year % 400) == 0:
    print('{0} is a leap year'.format(year))
else:
    print('{0} is not a leap year'.format(year))

In [52]:
multiples=[1,2,3,4,5,6,7,8,9,10]
num=int(input('enter num : '))



enter num : 1


In [53]:
output=list(map(lambda number:number*num,multiples))
print(output)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [54]:
import numpy as np

## OOps Concept in Python

In [1]:
# Class 
# Objects
# --init--()
# self

In [2]:
class Class1:   # Class definition
    a=3

In [3]:
obj=Class1()   #  object , to access that class

In [5]:
obj.a            # we are fetching the value inside that class

3

In [6]:
class Class1:   # Class definition
    a=3

    
obj=Class1() 
obj.a     

3

## ___init()___ function
* To assign the values to the objects

In [7]:
class Person:
    def __init__(self, name , age):
        self.name= name
        self.age= age

obj1= Person("ABC",30)
obj1.name

'ABC'

In [8]:
obj1.age

30

In [23]:
class Employee:
    def __init__(self, name, eid):
        self.name=name
        self.eid=eid
        
    def display(self):
        print("Employee name is", self.name)
        print("Employee id is: ", self.eid)
        
        

e1= Employee("Pavan", 101)
e2=Employee("Sandhya", 102)

e2.display()
        

Employee name is Sandhya
Employee id is:  102


In [16]:
def fun1():
    return 1
fun1()

1

In [29]:
class class1:
    
    def __init__(self):
        
        print("Constructor1 is running")
        
    def __init__(self):
        print("Constructor 2 is running")
        
c1=class1() 

# We don't have the concept of constructor overloading in Python.

Constructor 2 is running


## getattr(), setattr(), delattr(), hasattr()

In [30]:
class Employee1:
    def __init__(self, name, eid, age):
        self.name=name
        self.eid=eid
        self.age=age
        
emp1= Employee1("Sandhya",101, 23)

getattr(emp1,'name')

'Sandhya'

In [31]:
getattr(emp1,'age')

23

In [32]:
setattr(emp1,'age',22)

In [33]:
getattr(emp1,'age')

22

In [34]:
hasattr(emp1, 'eid')

True

In [35]:
delattr(emp1,'eid')

In [36]:
hasattr(emp1, 'eid')

False

## Inheritance

In [38]:
class Person:
    def __init__(self, fname, lname):
        self.firstname=fname
        self.lastname= lname
        
    def displayname(self):
        print(self.firstname,self.lastname)
        
p1=Person("Krishna","Patil")
p1.displayname()

Krishna Patil


In [41]:
class Employee(Person):
    def __init__(self,fname,lname,joining_yr):
        super().__init__(fname,lname)
        
        self.joining_year=joining_yr
    
    def display(self):
        print(self.firstname,self.lastname, self.joining_year)
        
        

In [44]:
p1 = Employee("Pavan","Kumar",2021)
p1.display()

Pavan Kumar 2021


## Multi-level Inheritance

In [45]:
class Animal:
    def speak(self):
        print("speak function running")
        
class Dog(Animal):
    def bark(self):
        print("Dog barks")

class Puppy(Dog):
    def drink(self):
        print("puppy drinks milk")

        
p= Puppy()

In [46]:
p.drink()

puppy drinks milk


In [47]:
p.bark()

Dog barks


In [48]:
p.speak()

speak function running


## Multiple Inheritance:

In [49]:
class ArithmeticOperation1:
    def Addition(self,i,j):
        return i+j
    
class ArithmeticOperation2:
    def Multiple(self,i,j):
        return i*j
    
class Derived(ArithmeticOperation1,ArithmeticOperation2):
    def subtract(self,i,j):
        return i-j
    
d=Derived()

    

In [50]:
d.Addition(10,20)

30

In [51]:
d.Multiple(10,20)

200

In [53]:
d.Multiple(1 * 0/0)

ZeroDivisionError: division by zero

In [61]:
try:
    print( block)
except NameError:
    print("Give the string in double quotes")
    
except:
    print("There is some other errors")

IndentationError: expected an indented block (<ipython-input-61-454572921700>, line 2)

In [64]:
try:
    f=open("file1.txt","r")

    
finally:
    print("Can't open the file bcs its not present")

Can't open the file bcs its not present


FileNotFoundError: [Errno 2] No such file or directory: 'file1.txt'

In [65]:
## raise the exception

n=-2

if n<0:
    raise Exception("Your number is negative")
    



Exception: Your number is negative

In [70]:
## String Formating:


#format()

n=20
m="Name"

print("The number is {} ".format(n) )

The number is 20 


In [71]:
msg=" The name is {fname}, Age is {age}".format(fname="Priya",age=22)

In [72]:
msg

' The name is Priya, Age is 22'

In [74]:
msg=" The name is {fname}, Age is {age}".format(age=22,fname="Priya")

In [75]:
msg

' The name is Priya, Age is 22'

In [79]:
msg=" The name is {}, Age is {}".format("Priya",22)

In [80]:
msg

' The name is Priya, Age is 22'

In [81]:
import pandas as pd

In [82]:
pd.read_csv("iris.csv")

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [83]:
import numpy as np
lst1=[1,2,3,4,5]
arr=np.array(lst1)
arr

array([1, 2, 3, 4, 5])

In [89]:
arr[3]

4

In [84]:
type(arr)

numpy.ndarray

In [88]:
arr.shape

(5,)

In [85]:

lst2=[1,2,3,4,5]
lst3=[2,3,4,5,6]
lst4=[9,7,6,8,9]
arr1=np.array([lst2,lst3,lst4])
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [86]:
type(arr1)

numpy.ndarray

In [87]:
arr1.shape

(3, 5)

In [91]:
arr1[2][3]

8

In [92]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])